// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// simulateHawkes
std::vector<std::vector<double> > simulateHawkes(SEXP lambda0, SEXP alpha, SEXP beta, SEXP horizon);
RcppExport SEXP hawkes_simulateHawkes(SEXP lambda0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type lambda0(lambda0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type horizon(horizonSEXP );
        std::vector<std::vector<double> > __result = simulateHawkes(lambda0, alpha, beta, horizon);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// jumpMean
std::vector<double> jumpMean(SEXP lambda0, SEXP alpha, SEXP beta, SEXP tau);
RcppExport SEXP hawkes_jumpMean(SEXP lambda0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type lambda0(lambda0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type tau(tauSEXP );
        std::vector<double> __result = jumpMean(lambda0, alpha, beta, tau);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// jumpVariance
arma::mat jumpVariance(SEXP lambda0, SEXP alpha, SEXP beta, SEXP tau);
RcppExport SEXP hawkes_jumpVariance(SEXP lambda0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type lambda0(lambda0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type tau(tauSEXP );
        arma::mat __result = jumpVariance(lambda0, alpha, beta, tau);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// jumpAutocorrelation
arma::mat jumpAutocorrelation(SEXP lambda0, SEXP alpha, SEXP beta, SEXP tau, SEXP lag);
RcppExport SEXP hawkes_jumpAutocorrelation(SEXP lambda0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP tauSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type lambda0(lambda0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type tau(tauSEXP );
        Rcpp::traits::input_parameter< SEXP >::type lag(lagSEXP );
        arma::mat __result = jumpAutocorrelation(lambda0, alpha, beta, tau, lag);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// likelihoodHawkes
double likelihoodHawkes(SEXP lambda0, SEXP alpha, SEXP beta, SEXP history);
RcppExport SEXP hawkes_likelihoodHawkes(SEXP lambda0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP historySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type lambda0(lambda0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type history(historySEXP );
        double __result = likelihoodHawkes(lambda0, alpha, beta, history);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
